import { Playlist } from '../interfaces/all.interface';

export const PLAYLISTS: Playlist[] = [
  { id: 1, name: 'Best Naija Music', platform: 'YouTube', numOfFollowers: '1,794', cost: 'Free', acceptanceRate: '67', rating: 2},
  { id: 2, name: 'Purple Tunes', platform: 'SoundCloud', numOfFollowers: '4,638', cost: 'Free', acceptanceRate: '96', rating: 4},
  { id: 3, name: 'BmusicTV', platform: 'YouTube', numOfFollowers: '43,309', cost: 'Free', acceptanceRate: '25', rating: 4},
  { id: 4, name: 'Destination Afrobeats', platform: 'YouTube', numOfFollowers: '19,537', cost: 'Free', acceptanceRate: '78', rating: 4},
  { id: 5, name: 'Purple Tunes', platform: 'YouTube', numOfFollowers: '3,625', cost: 'Free', acceptanceRate: '87', rating: 4},
  { id: 6, name: 'AfroMuzikWorldwide', platform: 'SoundCloud', numOfFollowers: '5,109', cost: 'Free', acceptanceRate: '78', rating: 4},
  { id: 7, name: 'Afro Songs', platform: 'SoundCloud', numOfFollowers: '1,392', cost: 'Free', acceptanceRate: '99', rating: 2},
  { id: 8, name: 'BmusicTV1', platform: 'SoundCloud', numOfFollowers: '1,919', cost: 'Free', acceptanceRate: '37', rating: 1},
  { id: 9, name: 'MusicPlug Africa', platform: 'SoundCloud', numOfFollowers: '485', cost: 'Free', acceptanceRate: '95', rating: 1},
  { id: 7, name: 'DjMiCHY™', platform: 'SoundCloud', numOfFollowers: '129', cost: 'Free', acceptanceRate: '99', rating: 1},
  { id: 8, name: 'Purple Tunes2', platform: 'SoundCloud', numOfFollowers: '1,627', cost: 'Free', acceptanceRate: '80', rating: 3},
  { id: 9, name: 'BmusicTV', platform: 'SoundCloud', numOfFollowers: '3,645', cost: 'Free', acceptanceRate: '21', rating: 2},
  { id: 10, name: 'Destination Afrobeats', platform: 'SoundCloud', numOfFollowers: '1,598', cost: 'Free', acceptanceRate: '78', rating: 4},
  { id: 11, name: 'Purple Tunes', platform: 'YouTube', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 4},
  { id: 7, name: 'Dancehall & Reggae CloudPro Unlimited', platform: 'SoundCloud', numOfFollowers: '39.8k', cost: '12', acceptanceRate: '88', rating: 2},
  { id: 13, name: 'Afrobeat360', platform: 'SoundCloud', numOfFollowers: '32.3k', cost: '52', acceptanceRate: '87', rating: 5},
  { id: 8, name: 'Dancehall and Reggae TV', platform: 'SoundCloud', numOfFollowers: '3,328', cost: '12', acceptanceRate: '88', rating: 2},
  { id: 9, name: 'Dancehall Repost Channel', platform: 'SoundCloud', numOfFollowers: '228', cost: 'Free', acceptanceRate: '45', rating: 2},
  { id: 10, name: 'Nigeria Jamz', platform: 'YouTube', numOfFollowers: '35,423', cost: '15', acceptanceRate: '35', rating: 4},
  { id: 7, name: 'Latest Nigerian Music', platform: 'YouTube', numOfFollowers: '62,992', cost: '15', acceptanceRate: '47', rating: 4},
  { id: 8, name: 'Sound Villa', platform: 'YouTube', numOfFollowers: '3,189', cost: 'Free', acceptanceRate: '35', rating: 2},
  { id: 9, name: 'Naija New Music updates', platform: 'YouTube', numOfFollowers: '1,518', cost: 'Free', acceptanceRate: '25', rating: 1},
  { id: 10, name: 'NetNaija Music', platform: 'YouTube', numOfFollowers: '4,355 ', cost: 'Free', acceptanceRate: '46', rating: 3},
  { id: 11, name: 'Purple Tunes2', platform: 'YouTube', numOfFollowers: '1,454', cost: 'Free', acceptanceRate: '75', rating: 2},
];
