import { Playlist } from '../interfaces/all.interface';

export const PLAYLISTS: Playlist[] = [
  { id: 1, name: 'Afrobeats all round', platform: 'SoundCloud', numOfFollowers: '32.3k', cost: '45', acceptanceRate: '45', rating: 3},
  { id: 2, name: 'Purple Tunes', platform: 'SoundCloud', numOfFollowers: '4,638', cost: '25', acceptanceRate: '45', rating: 1},
  { id: 3, name: 'musicB', platform: 'SoundCloud', numOfFollowers: '3,637', cost: '45', acceptanceRate: '45', rating: 3},
  { id: 4, name: 'Destination Afrobeats', platform: 'YouTube', numOfFollowers: '13,545', cost: '45', acceptanceRate: '45', rating: 3},
  { id: 5, name: 'Purple Tunes', platform: 'YouTube', numOfFollowers: '3,105', cost: '45', acceptanceRate: '45', rating: 4},
  { id: 6, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 1},
  { id: 7, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 1},
  { id: 8, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 2},
  { id: 9, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 3},
  { id: 10, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 4},
  { id: 11, name: 'Purple Tunes', platform: 'YouTube', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 4},
  { id: 7, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 1},
  { id: 8, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 2},
  { id: 9, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 3},
  { id: 10, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 4},
  { id: 11, name: 'Purple Tunes', platform: 'YouTube', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 4},
  { id: 7, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 1},
  { id: 8, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 2},
  { id: 9, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 3},
  { id: 10, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 4},
  { id: 11, name: 'Purple Tunes', platform: 'YouTube', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 4},
  { id: 7, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 1},
  { id: 8, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 2},
  { id: 9, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 3},
  { id: 10, name: 'Afrobeats', platform: 'SoundCloud', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 4},
  { id: 11, name: 'Purple Tunes', platform: 'YouTube', numOfFollowers: '35,545', cost: '45', acceptanceRate: '45', rating: 4},
];
